[FEATURE] Intégration de la page tutoriel (PIX-4981).
1024pix/pix-tutos pull request #12
Opened 2022-06-13 12:50 UTC by VincentHardouin

## :unicorn: Problème
La page d'un tutoriel n'est pour l'instant pas stylisée.

## :robot: Solution
Faire l'intégration de la page en suivant la maquette Figma. 

- Ajout des fonts dans les assets : Open Sans et Roboto 
- Ajout de 2 composants : `PixTutorial` et `PixButtonLink`. 
- Utilisation de la librairie : `modern-normalize`qui nous permettra d'avoir une version à jour constamment. 
- Ajout du package `@nuxtjs/styleResources` : pour avoir les variables sass en global.

## :rainbow: Remarques
> _Des infos supplémentaires, trucs et astuces ?_

## :100: Pour tester
- Se rendre sur un tutoriel et constater que l'intégration a été respecté à l'exception des tuiles du background.

2022-06-13 15:07 UTC, yannbertrand commented on layouts/default.vue
> +      <img src="~/assets/images/pix-logo.svg" class="main-header__logo" alt="Pix" />
Je me demande si les `alt` qu'on a ajouté ne polluent pas plus qu'autre chose l'expérience des screen readers 🤔 

```suggestion
      <img src="~/assets/images/marianne-logo.svg" class="main-header__logo" alt="" />
      <img src="~/assets/images/pix-logo.svg" class="main-header__logo" alt="" />
```

2022-06-13 15:09 UTC, yannbertrand commented on pages/_slug.vue
> +    video-dl-href="page.videoDLHref"
Petit oubli
```suggestion
    :video-dl-href="page.videoDLHref"
```

2022-06-13 15:11 UTC, yannbertrand commented on layouts/default.vue
> +      <img src="~/assets/images/pix-logo.svg" class="main-header__logo" alt="Pix" />
Attention, on a ajouté l'image dans `assets` directement aussi

2022-06-13 15:24 UTC, Jeyffrey commented on layouts/default.vue
> +      <img src="~/assets/images/pix-logo.svg" class="main-header__logo" alt="Pix" />
Done

2022-06-13 15:40 UTC, matthiasferraina approved these changes
🚀

2022-06-13 15:40 UTC, Jeyffrey approved these changes

2022-06-13 15:47 UTC, yannbertrand requested changes

2022-06-13 15:47 UTC, yannbertrand commented on components/PixTutorial.vue
> +        <PixButtonLink :href="videoDlHref" target="_blank">
https://stackoverflow.com/questions/50709625/link-with-target-blank-and-rel-noopener-noreferrer-still-vulnerable
```suggestion
        <PixButtonLink :href="videoDlHref" target="_blank" rel="noopener noreferrer">
```

2022-06-13 15:47 UTC, yannbertrand commented on components/PixTutorial.vue
> +        <PixButtonLink :href="fichePdfHref" target="_blank">
https://stackoverflow.com/questions/50709625/link-with-target-blank-and-rel-noopener-noreferrer-still-vulnerable
```suggestion
        <PixButtonLink :href="fichePdfHref" target="_blank" rel="noopener noreferrer">
```

2022-06-13 15:47 UTC, yannbertrand commented on components/PixTutorial.vue
> +          target="_blank"
```suggestion
          target="_blank"
          rel="noopener noreferrer"
```

2022-06-13 16:05 UTC, yannbertrand commented on layouts/default.vue
> +            alt=""
```suggestion
            alt="Pix"
```

2022-06-14 07:24 UTC, alexandrecoin commented on components/PixTutorial.vue
> +  <section class="tuto">
```suggestion
  <section>
```
Je n'ai pas l'impression que cette classe soit utile hormis nommage pour BEM.

2022-06-14 07:25 UTC, alexandrecoin approved these changes

2022-06-14 07:38 UTC, VincentHardouin commented on components/PixTutorial.vue
> +  <section class="tuto">
C'est suffisant non ? ;)

2022-06-14 07:49 UTC, yannbertrand approved these changes

2022-06-14 07:49 UTC, merged